apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-patch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
spec:
  project: default
  source:
    repoURL: https://github.com/recomendapp/infra.git
    targetRevision: main
    path: cluster/services/traefik-patch
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # Traefik service is often in kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
