apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imgproxy
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - imgproxy.recomend.app
      secretName: imgproxy-tls
  rules:
    - host: imgproxy.recomend.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: imgproxy
                port:
                  number: 80
