apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      imagePullSecrets:
        - name: github-credentials
      containers:
        - name: notify
          image: ghcr.io/recomendapp/notify@sha256:3af41699bfceefb54847a398f25ade61ba2e4d4cd085cc1c595bcefe9228babb
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: API_KEY

            - name: NOVU_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: NOVU_SECRET_KEY

            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: SUPABASE_URL

            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: SUPABASE_SERVICE_ROLE_KEY

            - name: NOVU_PROVIDER_ID_FCM
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: NOVU_PROVIDER_ID_FCM

            - name: NOVU_PROVIDER_ID_EXPO
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: NOVU_PROVIDER_ID_EXPO

            - name: NOVU_PROVIDER_ID_APNS
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: NOVU_PROVIDER_ID_APNS
