apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/name: traefik-lb
    load-balancer.hetzner.cloud/use-private-ip: "false"
spec:
  type: LoadBalancer