apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: martin
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - martin-new.recomend.app
      secretName: martin-tls
  rules:
    - host: martin-new.recomend.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: martin
                port:
                  number: 80
