apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - secret.yaml

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 3.2.2
    releaseName: velero
    valuesFile: values.yaml
