installCRDs: true

deployNodeAgent: true

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: "recomend-backups"
      config:
        region: auto
        s3ForcePathStyle: "true"
        s3Url: "https://c960e9a51b5b0decbfee92d753e153b0.r2.cloudflarestorage.com"

  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: auto

  defaultVolumesToFsBackup: false

credentials:
  useSecret: true
  existingSecret: velero-credentials
  secretContents:
    cloud: ""

extraPlugins:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.9.0

schedules:
  daily:
    disabled: false
    schedule: "0 2 * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: "720h"
      includedNamespaces:
        - "*"
      excludedNamespaces:
        - velero
