apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefect
  namespace: prefect
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - prefect.recomend.app
      secretName: prefect-tls
  rules:
    - host: prefect.recomend.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prefect-server
                port:
                  number: 4200
