apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: typsense-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - typesense-new.recomend.app
      secretName: typesense-tls
  rules:
    - host: typesense-new.recomend.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: typesense
                port:
                  number: 8108