apiVersion: apps/v1
kind: Deployment
metadata:
  name: martin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: martin
  template:
    metadata:
      labels:
        app: martin
    spec:
      imagePullSecrets:
        - name: github-credentials
      containers:
        - name: martin
          image: ghcr.io/recomendapp/martin@sha256:e1b37292818e9ac22eb2b03671bd72e8ba8f95d9a1415c9fb3391f264d3eba9f
          imagePullPolicy: Always
          args: ["--config", "/config.yaml"]
          ports:
            - containerPort: 3000