apiVersion: apps/v1
kind: Deployment
metadata:
  name: martin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: martin
  template:
    metadata:
      labels:
        app: martin
    spec:
      imagePullSecrets:
        - name: github-credentials
      containers:
        - name: martin
          image: ghcr.io/recomendapp/martin:20251125003859
          imagePullPolicy: Always
          args: ["--config", "/config.yaml"]
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1"